spring:
  datasource:
    url: jdbc:postgresql://192.168.100.4:54320/schedule_db
    username: user
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update